// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: test1

#ifndef _TEST1_UI_H
#define _TEST1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Image2;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Image3;
// CUSTOM VARIABLES

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_p1_png);    // assets/p1.png
LV_IMG_DECLARE(ui_img_p2_png);    // assets/p2.png
LV_IMG_DECLARE(ui_img_p3_png);    // assets/p3.png
LV_IMG_DECLARE(ui_img_3_png);    // assets/3.png
LV_IMG_DECLARE(ui_img_car_anim_01_png);    // assets/car_anim_01.png
LV_IMG_DECLARE(ui_img_car_anim_02_png);    // assets/car_anim_02.png
LV_IMG_DECLARE(ui_img_car_anim_03_png);    // assets/car_anim_03.png
LV_IMG_DECLARE(ui_img_car_anim_04_png);    // assets/car_anim_04.png
LV_IMG_DECLARE(ui_img_car_anim_05_png);    // assets/car_anim_05.png
LV_IMG_DECLARE(ui_img_car_anim_06_png);    // assets/car_anim_06.png
LV_IMG_DECLARE(ui_img_car_anim_07_png);    // assets/car_anim_07.png
LV_IMG_DECLARE(ui_img_car_anim_08_png);    // assets/car_anim_08.png
LV_IMG_DECLARE(ui_img_car_anim_09_png);    // assets/car_anim_09.png
LV_IMG_DECLARE(ui_img_car_anim_10_png);    // assets/car_anim_10.png
LV_IMG_DECLARE(ui_img_car_anim_11_png);    // assets/car_anim_11.png
LV_IMG_DECLARE(ui_img_car_anim_12_png);    // assets/car_anim_12.png
LV_IMG_DECLARE(ui_img_car_anim_13_png);    // assets/car_anim_13.png
LV_IMG_DECLARE(ui_img_car_anim_14_png);    // assets/car_anim_14.png
LV_IMG_DECLARE(ui_img_car_anim_15_png);    // assets/car_anim_15.png
LV_IMG_DECLARE(ui_img_car_anim_16_png);    // assets/car_anim_16.png
LV_IMG_DECLARE(ui_img_car_anim_17_png);    // assets/car_anim_17.png
LV_IMG_DECLARE(ui_img_car_anim_18_png);    // assets/car_anim_18.png
LV_IMG_DECLARE(ui_img_car_anim_19_png);    // assets/car_anim_19.png
LV_IMG_DECLARE(ui_img_car_anim_20_png);    // assets/car_anim_20.png
LV_IMG_DECLARE(ui_img_car_anim_21_png);    // assets/car_anim_21.png
LV_IMG_DECLARE(ui_img_2_png);    // assets/2.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
